version: '3'

services:
  db:
    image: postgres:14.5-alpine
    container_name: postgresdb
    environment:
      LANG: "pt_BR.utf8"
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
